spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: javatechie


  kafka:
    bootstrap-servers: localhost:9092   # Kafka broker addresses
    # Producer settings (for sending events)
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer    # Serializer for the key
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # Serializer for the value (event)
#      acks: all  # Ensure all replicas acknowledge the message
#      retries: 3 # Number of retries in case of failure
#      batch-size: 16384   # Batch size in bytes
#      linger-ms: 1        # Time to wait before sending a batch
#      buffer-memory: 33554432 # Buffer size in memory

    consumer:
      group-id: shipping-service    # Group ID for the consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer  # Deserializer for the key
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer  # Wraps JsonDeserializer for error handling
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"  # You can restrict this to your package for added security




shipping:
  event:
    topicName: shipping-events